### PR TITLE
Concat array properties when arrays are merged

### PR DESCRIPTION
**Pull request by nthornton2010**
- Switched mergeDeepLeft to mergeDeepWithKey to add array concatenation support within a merged result.

- Moved the logic in generateMerged into mergeModules and renamed generateMerged to printMerged since the merging is already done by the point print is called. Prior to this change, running the 'merged' command would result in merging happening twice (once in the constructor and then again in the hook) and duplicates appearing in merged arrays.

### CODE REVIEW

**Comment by nthornton2010** [comment]
I created this PR because I'm trying to use this plugin to merge a lambdaAccessPolicy (a resource) with nested PolicyDocument Statements (which is an array). The Statements from 1 module overwrite the Statements in other modules because of the nature of mergeDeepLeft. Using mergeDeepWithKey along with a custom reducer specifically for arrays fixes this issue and the merged file contains the correctly merged Statements array.

While testing, I noticed that initially all of my arrays contained duplicates. This was because the merge was occurring twice per call, once in the constructor and then again via the command's function. I opted to leave the merging in the constructor and just have the command output what was already done. I'd also be fine with the merge not being in the constructor, I wasn't sure what would be preferred.

**Comment by icarus-sullivan** [comment]
@nthornton2010 I made a new branch with some of your changes. I want to write a test for it, is there anyway you can provide a sanitized version of the issue you are facing so that I can reproduce it?

**Comment by nthornton2010** [comment]
@icarus-sullivan here's an example project along with an expected results file and actual results file that was created with the code prior to any of my changes.

The 2 spots that are different between files are:
- custom.appSync.dataSources
- resources.Resources.lambdaAccessPolicy.Properties.PolicyDocument.Statement

Both of the above have arrays as values. Prior to my change, only the first value in each array is returned. After my change, all values are concatenated and returned.

[modularize-test.zip](https://github.com/icarus-sullivan/serverless-plugin-modularize/files/5146822/modularize-test.zip)

**Comment by icarus-sullivan** [comment]
@nthornton2010 Thanks for supplying the zip file. I went through and added your examples to the `example` project in this repo with your suggestions. That work is here => https://github.com/icarus-sullivan/serverless-plugin-modularize/pull/8

I will be deploying 1.0.9 soon, please let me know if your issue is resolved.

**Comment by nthornton2010** [comment]
@icarus-sullivan I've updated my project to use 1.0.9 and everything seems to work as expected now! Thanks for the help!

**Pull request closed without merging**
